global_costmap:
   global_frame: map
   robot_base_frame: robot_footprint
   update_frequency: 1.5
   publish_frequency: 1.5
   width: 30.0
   height: 30.0
   resolution: 0.03
   static_map: true
   rolling_window: false
