global_costmap:
   global_frame: map
   robot_base_frame: robot_footprint
   update_frequency: 1
   publish_frequency: 1
   width: 30.0
   height: 30.0
   resolution: 0.01
   static_map: true
   rolling_window: false
